version: '3.4'

services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  communicationdb:
    container_name: communicationdb
    environment:
        SA_PASSWORD: "Pwd12345!"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  communicationtest:
    container_name: communicationtest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Default=Server=communicationdb;Database=CommunicationDb;User Id=sa;Password=Pwd12345!"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
        - communicationdb
        - rabbitmq
    ports:
      - "5000:80"

  rabbitmq.consumertest:
    container_name: rabbitmq.consumertest    
    environment:
        - "ConnectionStrings:Default=Server=communicationdb;Database=CommunicationDb;User Id=sa;Password=Pwd12345!"
        - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
        - communicationdb
        - rabbitmq
