version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

  communicationdb:
    image: mcr.microsoft.com/mssql/server

  communicationtest:
    image: ${DOCKER_REGISTRY-}communicationtest
    build:
      context: .
      dockerfile: CommunicationTest/Dockerfile

  rabbitmq.consumertest:
    image: ${DOCKER_REGISTRY-}rabbitmqconsumertest
    build:
      context: .
      dockerfile: RabbitMQ.ConsumerTest/Dockerfile

volumes:
  communication_data:
